const t = require("./types").types;

module.exports.characters = {
  // Triask's Characters
  "Shisk" : {
    name: "Shisk",
    owner : "Triask.4189",
    armor : "light",
    combat : "magic",
    class: "necromancer",
    specialization : "none",
    min_rank: 3,
    max_rank: 6,
    hp_modifier: 1.3,
    spd_modifier: 0.9,
    atk_modifier: 1,
    def_modifier: 1.2,
    pull_group: 3 //ext
  },
  "Condi Scourge Shisk" : {
    name: "Condi Scourge Shisk",
    owner : "Triask.4189",
    armor : "light",
    combat : "magic",
    class: "necromancer",
    specialization : "scourge",
    min_rank: 4,
    max_rank: 7,
    hp_modifier: 1.1,
    spd_modifier: 1.1,
    atk_modifier: 1.2,
    def_modifier: 1.1,
    pull_group: 1 //ext
  },
  "Power Reaper Shisk" : {
    name: "Power Reaper Shisk",
    owner : "Triask.4189",
    armor : "light",
    combat : "melee",
    class: "necromancer",
    specialization : "scourge",
    min_rank: 4,
    max_rank: 7,
    hp_modifier: 1.2,
    spd_modifier: 0.8,
    atk_modifier: 1.3,
    def_modifier: 1.2,
    pull_group: 1 //ext
  },
  "Yilit" : {
    name: "Yilit",
    owner : "Triask.4189",
    armor : "light",
    combat : "melee",
    class: "mesmer",
    specialization : "none",
    min_rank: 3,
    max_rank: 5,
    hp_modifier: 1.1,
    spd_modifier: 0.9,
    atk_modifier: 1,
    def_modifier: 1.2,
    pull_group: 4 //ext
  },
  "Chrono Tank Yilit" : {
    name: "Chrono Tank Yilit",
    owner : "Triask.4189",
    armor : "light",
    combat : "melee",
    class: "mesmer",
    specialization : "chrono",
    min_rank: 3,
    max_rank: 6,
    hp_modifier: 1.3,
    spd_modifier: 0.9,
    atk_modifier: 0.9,
    def_modifier: 1.4,
    pull_group: 1 //ext
  },
  "Condi Mirage Yilit" : {
    name: "Condi Mirage Yilit",
    owner : "Triask.4189",
    armor : "light",
    combat : "melee",
    class: "mesmer",
    specialization : "mirage",
    min_rank: 3,
    max_rank: 6,
    hp_modifier: 1.1,
    spd_modifier: 1.3,
    atk_modifier: 1.3,
    def_modifier: 0.8,
    pull_group: 1 //ext
  },
  "Zipts" : {
    name: "Zipts",
    owner : "Triask.4189",
    armor : "heavy",
    combat : "melee",
    class: "guardian",
    specialization : "firebrand",
    min_rank: 3,
    max_rank: 6,
    hp_modifier: 0.9,
    spd_modifier: 1.2,
    atk_modifier: 1.3,
    def_modifier: 0.9,
    pull_group: 1 //ext
  },
  "Firebrand Healer Zipts" : {
    name: "Firebrand Healer Zipts",
    owner : "Triask.4189",
    armor : "heavy",
    combat : "melee",
    class: "guardian",
    specialization : "firebrand",
    min_rank: 3,
    max_rank: 6,
    hp_modifier: 1.4,
    spd_modifier: 1.2,
    atk_modifier: 0.8,
    def_modifier: 1.0,
    pull_group: 1 //ext
  },
  "Izieko" : {
    name: "Izieko",
    owner : "Triask.4189",
    armor : "medium",
    combat : "magic",
    class: "ranger",
    specialization : "none",
    min_rank: 2,
    max_rank: 5,
    hp_modifier: 1.1,
    spd_modifier: 1.0,
    atk_modifier: 1.1,
    def_modifier: 1.0,
    pull_group: 5 //ext
  },
  "Yeukrin" : {
    name: "Yeukrin",
    owner : "Triask.4189",
    armor : "medium",
    combat : "melee",
    class: "engineer",
    specialization : "none",
    min_rank: 2,
    max_rank: 5,
    hp_modifier: 1.0,
    spd_modifier: 1.0,
    atk_modifier: 1.2,
    def_modifier: 1.0,
    pull_group: 5 //ext
  },
  "Qucul" : {
    name: "Qucul",
    owner : "Triask.4189",
    armor : "heavy",
    combat : "magic",
    class: "revenant",
    specialization : "none",
    min_rank: 2,
    max_rank: 5,
    hp_modifier: 1.1,
    spd_modifier: 0.9,
    atk_modifier: 1,
    def_modifier: 1.2,
    pull_group: 5 //ext
  },
  "Xnitch" : {
    name: "Xnitch",
    owner : "Triask.4189",
    armor : "medium",
    combat : "melee",
    class: "thief",
    specialization : "none",
    min_rank: 1,
    max_rank: 4,
    hp_modifier: 0.9,
    spd_modifier: 1.3,
    atk_modifier: 1,
    def_modifier: 0.9,
    pull_group: 6 //ext
  },
  "Linyli" : {
    name: "Linyli",
    owner : "Triask.4189",
    armor : "heavy",
    combat : "ranged",
    class: "warrior",
    specialization : "none",
    min_rank: 1,
    max_rank: 4,
    hp_modifier: 1.1,
    spd_modifier: 0.9,
    atk_modifier: 1.1,
    def_modifier: 1.0,
    pull_group: 6 //ext
  },
  "Oquti" : {
    name: "Oquti",
    owner : "Triask.4189",
    armor : "light",
    combat : "magic",
    class: "elementalist",
    specialization : "none",
    min_rank: 1,
    max_rank: 3,
    hp_modifier: 0.8,
    spd_modifier: 0.9,
    atk_modifier: 1.4,
    def_modifier: 0.9,
    pull_group: 6 //ext
  },
  "Paired Deuces" : {
    name: "Paired Deuces",
    owner : "Triask.4189",
    armor : "medium",
    combat : "magic",
    class: "engineer",
    specialization : "none",
    min_rank: 1,
    max_rank: 3,
    hp_modifier: 0.8,
    spd_modifier: 0.9,
    atk_modifier: 1.2,
    def_modifier: 1.0,
    pull_group: 7 //ext
  },
  // Anzy's Units
  "Sylvia Aria" : {
    name: "Sylvia Aria",
    owner : "Anzy.9237",
    armor : "medium",
    combat : "melee",
    class: "thief",
    specialization : "none",
    min_rank: 3,
    max_rank: 6,
    hp_modifier: 0.9,
    spd_modifier: 1.3,
    atk_modifier: 1.3,
    def_modifier: 0.9,
    pull_group: 3 //ext
  },
  "Alssie" : {
    name: "Alssie",
    owner : "Anzy.9237",
    armor : "medium",
    combat : "magic",
    class: "ranger",
    specialization : "none",
    min_rank: 2,
    max_rank: 5,
    hp_modifier: 1.4,
    spd_modifier: 1.0,
    atk_modifier: 0.9,
    def_modifier: 1.0,
    pull_group: 4 //ext
  },
  "Deilusia" : {
    name: "Deilusia",
    owner : "Anzy.9237",
    armor : "light",
    combat : "melee",
    class: "mesmer",
    specialization : "none",
    min_rank: 2,
    max_rank: 5,
    hp_modifier: 1.2,
    spd_modifier: 0.9,
    atk_modifier: 0.9,
    def_modifier: 1.4,
    pull_group: 4 //ext
  },
  "Tybalt Ashpaw" : {
    name: "Tybalt Ashpaw",
    owner : "Anzy.9237",
    armor : "light",
    combat : "ranged",
    class: "elementalist",
    specialization : "none",
    min_rank: 2,
    max_rank: 5,
    hp_modifier: 0.8,
    spd_modifier: 1.0,
    atk_modifier: 1.6,
    def_modifier: 0.8,
    pull_group: 5 //ext
  },
  "Faira Cete" : {
    name: "Faira Cete",
    owner : "Anzy.9237",
    armor : "heavy",
    combat : "magic",
    class: "warrior",
    specialization : "none",
    min_rank: 3,
    max_rank: 4,
    hp_modifier: 1.0,
    spd_modifier: 1.0,
    atk_modifier: 1.2,
    def_modifier: 1.0,
    pull_group: 5 //ext
  },
  "Engienius" : {
    name: "Engienius",
    owner : "Anzy.9237",
    armor : "medium",
    combat : "melee",
    class: "engineer",
    specialization : "none",
    min_rank: 1,
    max_rank: 5,
    hp_modifier: 0.95,
    spd_modifier: 1.1,
    atk_modifier: 1.3,
    def_modifier: 0.9,
    pull_group: 5 //ext
  },
  "Living Phobia" : {
    name: "Living Phobia",
    owner : "Anzy.9237",
    armor : "light",
    combat : "magic",
    class: "necromancer",
    specialization : "none",
    min_rank: 1,
    max_rank: 4,
    hp_modifier: 1.1,
    spd_modifier: 0.9,
    atk_modifier: 1.0,
    def_modifier: 1.1,
    pull_group: 6 //ext
  },
  "Mimi Whyte" : {
    name: "Mimi Whyte",
    owner : "Anzy.9237",
    armor : "heavy",
    combat : "ranged",
    class: "guardian",
    specialization : "none",
    min_rank: 1,
    max_rank: 4,
    hp_modifier: 0.9,
    spd_modifier: 1.0,
    atk_modifier: 1.25,
    def_modifier: 0.9,
    pull_group: 6 //ext
  },
  "Mystical" : {
    name: "Mystical",
    owner : "Anzy.9237",
    armor : "heavy",
    combat : "magic",
    class: "revenant",
    specialization : "none",
    min_rank: 1,
    max_rank: 4,
    hp_modifier: 0.95,
    spd_modifier: 1.0,
    atk_modifier: 1.1,
    def_modifier: 1.0,
    pull_group: 6 //ext
  },
  "Wishful" : {
    name: "Wishful",
    owner : "Anzy.9237",
    armor : "light",
    combat : "ranged",
    class: "elementalist",
    specialization : "none",
    min_rank: 1,
    max_rank: 3,
    hp_modifier: 0.7,
    spd_modifier: 0.8,
    atk_modifier: 1.5,
    def_modifier: 0.8,
    pull_group: 7 //ext
  },
  "Anzer Panzer" : {
    name: "Anzer Panzer",
    owner : "Anzy.9237",
    armor : "heavy",
    combat : "ranged",
    class: "warrior",
    specialization : "none",
    min_rank: 1,
    max_rank: 3,
    hp_modifier: 1.0,
    spd_modifier: 0.9,
    atk_modifier: 1.0,
    def_modifier: 0.9,
    pull_group: 7 //ext
  },
  "Sketchy Art Student" : {
    name: "Sketchy Art Student",
    owner : "Anzy.9237",
    armor : "medium",
    combat : "magic",
    class: "ranger",
    specialization : "none",
    min_rank: 1,
    max_rank: 3,
    hp_modifier: 1.0,
    spd_modifier: 1.0,
    atk_modifier: 0.9,
    def_modifier: 0.9,
    pull_group: 3 //ext
  },
  "La Pestables" : {
    name: "La Pestables",
    owner : "Anzy.9237",
    armor : "medium",
    combat : "melee",
    class: "necromancer",
    specialization : "none",
    min_rank: 1,
    max_rank: 3,
    hp_modifier: 1.1,
    spd_modifier: 0.9,
    atk_modifier: 0.9,
    def_modifier: 0.9,
    pull_group: 7 //ext
  },
  // Peste's Units
  "La Peste" : {
    name: "La Peste",
    owner : "fluffnut.7624",
    armor : "light",
    combat : "magic",
    class: "necromancer",
    specialization : "none",
    min_rank: 3,
    max_rank: 6,
    hp_modifier: 1.3,
    spd_modifier: 0.95,
    atk_modifier: 1,
    def_modifier: 1.15,
    pull_group: 3 //ext
  },
  "Iced Peppermint Tea" : {
    name: "Iced Peppermint Tea",
    owner : "fluffnut.7624",
    armor : "medium",
    combat : "magic",
    class: "ranger",
    specialization : "none",
    min_rank: 2,
    max_rank: 5,
    hp_modifier: 1.4,
    spd_modifier: 0.9,
    atk_modifier: 0.9,
    def_modifier: 1.1,
    pull_group: 4 //ext
  },
  "Enfant de la Lune" : {
    name: "Enfant de la Lune",
    owner : "fluffnut.7624",
    armor : "heavy",
    combat : "melee",
    class: "warrior",
    specialization : "none",
    min_rank: 2,
    max_rank: 5,
    hp_modifier: 0.9,
    spd_modifier: 1.1,
    atk_modifier: 1.2,
    def_modifier: 1.1,
    pull_group: 4 //ext
  },
  "Tem Peste" : {
    name: "Tem Peste",
    owner : "fluffnut.7624",
    armor : "light",
    combat : "magic",
    class: "elementalist",
    specialization : "none",
    min_rank: 2,
    max_rank: 5,
    hp_modifier: 0.9,
    spd_modifier: 1,
    atk_modifier: 1.1,
    def_modifier: 1.2,
    pull_group: 5 //ext
  },
  "Chere Ophelie" : {
    name: "Chere Ophelie",
    owner : "fluffnut.7624",
    armor : "heavy",
    combat : "ranged",
    class: "guardian",
    specialization : "none",
    min_rank: 2,
    max_rank: 4,
    hp_modifier: 1.1,
    spd_modifier: 1.1,
    atk_modifier: 1.0,
    def_modifier: 1.05,
    pull_group: 5 //ext
  },
  "Christabel" : {
    name: "Christabel",
    owner : "fluffnut.7624",
    armor : "light",
    combat : "melee",
    class: "mesmer",
    specialization : "none",
    min_rank: 1,
    max_rank: 4,
    hp_modifier: 1.0,
    spd_modifier: 0.8,
    atk_modifier: 1.2,
    def_modifier: 1.0,
    pull_group: 6 //ext
  },
  "Revelries" : {
    name: "Revelries",
    owner : "fluffnut.7624",
    armor : "heavy",
    combat : "magic",
    class: "revenant",
    specialization : "none",
    min_rank: 1,
    max_rank: 5,
    hp_modifier: 0.9,
    spd_modifier: 0.95,
    atk_modifier: 1,
    def_modifier: 1.1,
    pull_group: 6 //ext
  },
  "Aeghbert" : {
    name: "Aeghbert",
    owner : "Liko.6825",
    armor : "medium",
    combat : "melee",
    class: "thief",
    specialization : "none",
    min_rank: 3,
    max_rank: 6,
    hp_modifier: 1.2,
    spd_modifier: 0.8,
    atk_modifier: 1.2,
    def_modifier: 1.2,
    pull_group: 3 //ext
  },
  "Eggizmo" : {
    name: "Eggizmo",
    owner : "Liko.6825",
    armor : "medium",
    combat : "melee",
    class: "engineer",
    specialization : "none",
    min_rank: 2,
    max_rank: 5,
    hp_modifier: 1.1,
    spd_modifier: 1.2,
    atk_modifier: 1.0,
    def_modifier: 1.0,
    pull_group: 4 //ext
  },
  "Pyroflora" : {
    name: "Pyroflora",
    owner : "Liko.6825",
    armor : "heavy",
    combat : "ranged",
    class: "guardian",
    specialization : "none",
    min_rank: 4,
    max_rank: 7,
    hp_modifier: 0.95,
    spd_modifier: 1.2,
    atk_modifier: 1.2,
    def_modifier: 1.1,
    pull_group: 3 //ext
  },
  "Chrysanthereal" : {
    name: "Chrysanthereal",
    owner : "Liko.6825",
    armor : "medium",
    combat : "ranged",
    class: "ranger",
    specialization : "none",
    min_rank: 1,
    max_rank: 3,
    hp_modifier: 0.95,
    spd_modifier: 1.0,
    atk_modifier: 1.1,
    def_modifier: 1.0,
    pull_group: 7 //ext
  },
  "Auri Chalcum" : {
    name: "Auri Chalcum",
    owner : "holypen0r.8639",
    armor : "heavy",
    combat : "magic",
    class: "revenant",
    specialization : "none",
    min_rank: 3,
    max_rank: 5,
    hp_modifier: 0.95,
    spd_modifier: 0.9,
    atk_modifier: 1.1,
    def_modifier: 1.3,
    pull_group: 4 //ext
  },
  "Cute Girl Gamer" : {
    name: "Cute Girl Gamer",
    owner : "holypen0r.8639",
    armor : "light",
    combat : "magic",
    class: "elementalist",
    specialization : "none",
    min_rank: 1,
    max_rank: 4,
    hp_modifier: 0.95,
    spd_modifier: 0.9,
    atk_modifier: 0.8,
    def_modifier: 1.1,
    pull_group: 6 //ext
  },
  "Bathea Keyblade" : {
    name: "Bathea Keyblade",
    owner : "holypen0r.8639",
    armor : "heavy",
    combat : "ranged",
    class: "guardian",
    specialization : "none",
    min_rank: 1,
    max_rank: 2,
    hp_modifier: 1.1,
    spd_modifier: 1.1,
    atk_modifier: 1.1,
    def_modifier: 1.1,
    pull_group: 7 //ext
  },
  "Ninja As Guardian" : {
    name: "Ninja As Guardian",
    owner : "IMA NINJA.4061",
    armor : "heavy",
    combat : "melee",
    class: "guardian",
    specialization : "none",
    min_rank: 3,
    max_rank: 6,
    hp_modifier: 1.3,
    spd_modifier: 0.9,
    atk_modifier: 1.15,
    def_modifier: 1.05,
    pull_group: 3 //ext
  },
  "Charred Bananas" : {
    name: "Charred Bananas",
    owner : "IMA NINJA.4061",
    armor : "heavy",
    combat : "magic",
    class: "warrior",
    specialization : "none",
    min_rank: 3,
    max_rank: 5,
    hp_modifier: 0.8,
    spd_modifier: 0.8,
    atk_modifier: 1.45,
    def_modifier: 1.15,
    pull_group: 4 //ext
  },
  "Combo Maker" : {
    name: "Combo Maker",
    owner : "IMA NINJA.4061",
    armor : "light",
    combat : "melee",
    class: "elementalist",
    specialization : "none",
    min_rank: 2,
    max_rank: 4,
    hp_modifier: 1.4,
    spd_modifier: 0.8,
    atk_modifier: 1.0,
    def_modifier: 1.0,
    pull_group: 5 //ext
  },
  "Neushmy" : {
    name: "Neushmy",
    owner : "cjsb.4569",
    armor : "medium",
    combat : "ranged",
    class: "ranger",
    specialization : "none",
    min_rank: 2,
    max_rank: 5,
    hp_modifier: 1.1,
    spd_modifier: 0.95,
    atk_modifier: 1.15,
    def_modifier: 1.1,
    pull_group: 4 //ext
  },
  "Ginviere" : {
    name: "Ginviere",
    owner : "cjsb.4569",
    armor : "light",
    combat : "magic",
    class: "elementalist",
    specialization : "none",
    min_rank: 1,
    max_rank: 3,
    hp_modifier: 0.9,
    spd_modifier: 0.9,
    atk_modifier: 1.2,
    def_modifier: 0.9,
    pull_group: 7 //ext
  },
  "Lucera Elstadt" : {
    name: "Lucera Elstadt",
    owner : "KCaScTiVCrMn.6453",
    armor : "medium",
    combat : "melee",
    class: "ranger",
    specialization : "none",
    min_rank: 3,
    max_rank: 6,
    hp_modifier: 1.0,
    spd_modifier: 0.8,
    atk_modifier: 1.5,
    def_modifier: 1.1,
    pull_group: 3 //ext
  },
  "A Is" : {
    name: "A Is",
    owner : "KCaScTiVCrMn.6453",
    armor : "medium",
    combat : "melee",
    class: "thief",
    specialization : "none",
    min_rank: 2,
    max_rank: 5,
    hp_modifier: 1.0,
    spd_modifier: 1.1,
    atk_modifier: 1.0,
    def_modifier: 1.2,
    pull_group: 4 //ext
  },
  "Lucera Silverlight" : {
    name: "Lucera Silverlight",
    owner : "KCaScTiVCrMn.6453",
    armor : "light",
    combat : "ranged",
    class: "elementalist",
    specialization : "none",
    min_rank: 1,
    max_rank: 5,
    hp_modifier: 1.1,
    spd_modifier: 1.15,
    atk_modifier: 1.0,
    def_modifier: 1.0,
    pull_group: 5 //ext
  },
  "Hemuhemu" : {
    name: "Hemuhemu",
    owner : "nintama.9436",
    armor : "light",
    combat : "magic",
    class: "necromancer",
    specialization : "none",
    min_rank: 3,
    max_rank: 6,
    hp_modifier: 1.2,
    spd_modifier: 1.3,
    atk_modifier: 0.8,
    def_modifier: 1.1,
    pull_group: 3 //ext
  },
  "Hemu W" : {
    name: "Hemu W",
    owner : "nintama.9436",
    armor : "heavy",
    combat : "melee",
    class: "warrior",
    specialization : "none",
    min_rank: 2,
    max_rank: 5,
    hp_modifier: 1.2,
    spd_modifier: 1.1,
    atk_modifier: 0.8,
    def_modifier: 1.2,
    pull_group: 4 //ext
  },
  "Creepy Heemu" : {
    name: "Creepy Heemu",
    owner : "nintama.9436",
    armor : "light",
    combat : "ranged",
    class: "necromancer",
    specialization : "none",
    min_rank: 1,
    max_rank: 4,
    hp_modifier: 1.0,
    spd_modifier: 1.0,
    atk_modifier: 1.0,
    def_modifier: 1.1,
    pull_group: 6 //ext
  },
  "Shiayi" : {
    name: "Shiayi",
    owner : "darkshia.5946",
    armor : "heavy",
    combat : "magic",
    class: "warrior",
    specialization : "none",
    min_rank: 3,
    max_rank: 6,
    hp_modifier: 1.2,
    spd_modifier: 1.1,
    atk_modifier: 0.9,
    def_modifier: 1.2,
    pull_group: 3 //ext
  },
  "Shia Umm" : {
    name: "Shia Umm",
    owner : "darkshia.5946",
    armor : "heavy",
    combat : "ranged",
    class: "guardian",
    specialization : "none",
    min_rank: 2,
    max_rank: 5,
    hp_modifier: 1.1,
    spd_modifier: 1.1,
    atk_modifier: 0.9,
    def_modifier: 1.2,
    pull_group: 4 //ext
  },
  "Faeyta" : {
    name: "Faeyta",
    owner : "darkshia.5946",
    armor : "medium",
    combat : "ranged",
    class: "ranger",
    specialization : "none",
    min_rank: 1,
    max_rank: 4,
    hp_modifier: 1.1,
    spd_modifier: 1.0,
    atk_modifier: 1.0,
    def_modifier: 1.0,
    pull_group: 6 //ext
  },
  "Panda Trident" : {
    name: "Panda Trident",
    owner : "unforeseen panda.6193",
    armor : "light",
    combat : "ranged",
    class: "warrior",
    specialization : "none",
    min_rank: 3,
    max_rank: 6,
    hp_modifier: 1.1,
    spd_modifier: 1.3,
    atk_modifier: 1.0,
    def_modifier: 1.0,
    pull_group: 3 //ext
  },
  "Asthenia" : {
    name: "Asthenia",
    owner : "unforeseen panda.6193",
    armor : "heavy",
    combat : "melee",
    class: "warrior",
    specialization : "none",
    min_rank: 3,
    max_rank: 5,
    hp_modifier: 1.0,
    spd_modifier: 1.1,
    atk_modifier: 1.05,
    def_modifier: 1.1,
    pull_group: 4 //ext
  },
  "Jugs Meowsers" : {
    name: "Jugs Meowsers",
    owner : "unforeseen panda.6193",
    armor : "light",
    combat : "ranged",
    class: "mesmer",
    specialization : "none",
    min_rank: 1,
    max_rank: 5,
    hp_modifier: 1.1,
    spd_modifier: 1.1,
    atk_modifier: 1.0,
    def_modifier: 1.0,
    pull_group: 6 //ext
  },
  "Kon Arrtist" : {
    name: "Kon Arrtist",
    owner : "DeafRadio.7402",
    armor : "medium",
    combat : "melee",
    class: "thief",
    specialization : "none",
    min_rank: 3,
    max_rank: 6,
    hp_modifier: 1.6,
    spd_modifier: 0.9,
    atk_modifier: 0.9,
    def_modifier: 1.0,
    pull_group: 3 //ext
  },
  "The Bacca" : {
    name: "The Bacca",
    owner : "DeafRadio.7402",
    armor : "light",
    combat : "ranged",
    class: "necromancer",
    specialization : "none",
    min_rank: 2,
    max_rank: 5,
    hp_modifier: 1.6,
    spd_modifier: 0.9,
    atk_modifier: 1.9,
    def_modifier: 1.9,
    pull_group: 4 //ext
  },
  "Fewshon" : {
    name: "Fewshon",
    owner : "DeafRadio.7402",
    armor : "medium",
    combat : "ranged",
    class: "ranger",
    specialization : "none",
    min_rank: 1,
    max_rank: 4,
    hp_modifier: 1.1,
    spd_modifier: 0.9,
    atk_modifier: 1.0,
    def_modifier: 1.1,
    pull_group: 6 //ext
  },
  "Aria Ciel" : {
    name: "Aria Ciel",
    owner : "Ramune.9813",
    armor : "medium",
    combat : "magic",
    class: "ranger",
    specialization : "none",
    min_rank: 3,
    max_rank: 6,
    hp_modifier: 1.0,
    spd_modifier: 1.0,
    atk_modifier: 1.4,
    def_modifier: 1.0,
    pull_group: 3 //ext
  },
  "Lunatic Rose" : {
    name: "Lunatic Rose",
    owner : "Ramune.9813",
    armor : "light",
    combat : "melee",
    class: "mesmer",
    specialization : "none",
    min_rank: 1,
    max_rank: 5,
    hp_modifier: 1.0,
    spd_modifier: 1.0,
    atk_modifier: 1.15,
    def_modifier: 1.0,
    pull_group: 5 //ext
  },
  "Artoria Lionheart" : {
    name: "Artoria Lionheart",
    owner : "Ramune.9813",
    armor : "heavy",
    combat : "ranged",
    class: "guardian",
    specialization : "none",
    min_rank: 1,
    max_rank: 3,
    hp_modifier: 1.0,
    spd_modifier: 1.0,
    atk_modifier: 1.0,
    def_modifier: 0.95,
    pull_group: 7 //ext
  },
  "Eevables" : {
    name: "Eevables",
    owner : "Eevables.1450",
    armor : "heavy",
    combat : "ranged",
    class: "guardian",
    specialization : "none",
    min_rank: 3,
    max_rank: 6,
    hp_modifier: 1.4,
    spd_modifier: 0.8,
    atk_modifier: 0.8,
    def_modifier: 1.4,
    pull_group: 3 //ext
  },
  "Mewsmurr" : {
    name: "Mewsmurr",
    owner : "Eevables.1450",
    armor : "light",
    combat : "ranged",
    class: "mesmer",
    specialization : "none",
    min_rank: 1,
    max_rank: 5,
    hp_modifier: 1.1,
    spd_modifier: 1.2,
    atk_modifier: 1.0,
    def_modifier: 1.0,
    pull_group: 4 //ext
  },
  "Austes Inmos" : {
    name: "Austes Inmos",
    owner : "Eevables.1450",
    armor : "heavy",
    combat : "melee",
    class: "warrior",
    specialization : "none",
    min_rank: 1,
    max_rank: 3,
    hp_modifier: 1.1,
    spd_modifier: 0.8,
    atk_modifier: 1.0,
    def_modifier: 1.0,
    pull_group: 7 //ext
  },
  "Aetherize" : {
    name: "Aetherize",
    owner : "xBlues.6581",
    armor : "heavy",
    combat : "ranged",
    class: "guardian",
    specialization : "none",
    min_rank: 1,
    max_rank: 5,
    hp_modifier: 1.0,
    spd_modifier: 1.1,
    atk_modifier: 1.0,
    def_modifier: 1.1,
    pull_group: 5 //ext
  },
  "Hinakou" : {
    name: "Hinakou",
    owner : "xBlues.6581",
    armor : "light",
    combat : "ranged",
    class: "elementalist",
    specialization : "none",
    min_rank: 1,
    max_rank: 5,
    hp_modifier: 1.05,
    spd_modifier: 1.1,
    atk_modifier: 1.0,
    def_modifier: 1.05,
    pull_group: 5 //ext
  },
  "Paladin Blues" : {
    name: "Paladin Blues",
    owner : "xBlues.6581",
    armor : "heavy",
    combat : "ranged",
    class: "guardian",
    specialization : "none",
    min_rank: 1,
    max_rank: 3,
    hp_modifier: 1.0,
    spd_modifier: 1.0,
    atk_modifier: 0.9,
    def_modifier: 1.0,
    pull_group: 7 //ext
  },/*
  "xxxxxx" : {
    name: "xxxxxx",
    owner : "xxxx.0000",
    armor : "medium",
    combat : "ranged",
    class: "warrior",
    specialization : "none",
    min_rank: 1,
    max_rank: 4,
    hp_modifier: 1.0,
    spd_modifier: 1.0,
    atk_modifier: 1.0,
    def_modifier: 1.0,
    pull_group: 3 //ext
  },*/
}
