const t = require("./types").types;

module.exports.characters = {
  "Shisk" : {
    name: "Shisk",
    owner : "Triask.4189",
    armor : "light",
    combat : "magic",
    class: "necro",
    specialization : "none",
    min_rank: 4,
    max_rank: 7,
    hp_modifier: 1.3,
    spd_modifier: 0.9,
    atk_modifier: 1,
    def_modifier: 1.2,
    pull_group: 1
  },
  "Sylvia Aria" : {
    name: "Sylvia Aria",
    owner : "Anzy.9237",
    armor : "medium",
    combat : "melee",
    class: "thief",
    specialization : "none",
    min_rank: 4,
    max_rank: 7,
    hp_modifier: 0.9,
    spd_modifier: 1.3,
    atk_modifier: 1.3,
    def_modifier: 0.9,
    pull_group: 2
  },
  "La Peste" : {
    name: "La Peste",
    owner : "fluffnut.7624",
    armor : "light",
    combat : "magic",
    class: "necro",
    specialization : "none",
    min_rank: 4,
    max_rank: 7,
    hp_modifier: 1.3,
    spd_modifier: 0.95,
    atk_modifier: 1,
    def_modifier: 1.15,
    pull_group: 3
  },
  "Aeghbert" : {
    name: "Aeghbert",
    owner : "Liko.6825",
    armor : "medium",
    combat : "melee",
    class: "thief",
    specialization : "none",
    min_rank: 4,
    max_rank: 7,
    hp_modifier: 0.95,
    spd_modifier: 1.2,
    atk_modifier: 1.2,
    def_modifier: 1.1,
    pull_group: 4
  },
  "Ninja As Guardian" : {
    name: "Ninja As Guardian",
    owner : "IMA NINJA.4061",
    armor : "heavy",
    combat : "melee",
    class: "guard",
    specialization : "none",
    min_rank: 4,
    max_rank: 7,
    hp_modifier: 1.3,
    spd_modifier: 0.9,
    atk_modifier: 1.15,
    def_modifier: 1.05,
    pull_group: 5
  },
  "Neushmy" : {
    name: "Neushmy",
    owner : "cjsb.4569",
    armor : "medium",
    combat : "ranged",
    class: "ranger",
    specialization : "none",
    min_rank: 2,
    max_rank: 5,
    hp_modifier: 1.1,
    spd_modifier: 0.95,
    atk_modifier: 1,
    def_modifier: 1.1,
    pull_group: 6
  },
  "Ginviere" : {
    name: "Ginviere",
    owner : "cjsb.4569",
    armor : "light",
    combat : "magic",
    class: "ele",
    specialization : "none",
    min_rank: 1,
    max_rank: 3,
    hp_modifier: 0.9,
    spd_modifier: 0.9,
    atk_modifier: 1.2,
    def_modifier: 0.9,
    pull_group: 7
  },
}
