const t = require("./types").types;

module.exports.characters = {
  // Triask's Characters
  "Shisk" : {
    name: "Shisk",
    owner : "Triask.4189",
    armor : "light",
    combat : "magic",
    class: "necromancer",
    specialization : "none",
    min_rank: 3,
    max_rank: 6,
    hp_modifier: 1.3,
    spd_modifier: 0.9,
    atk_modifier: 1,
    def_modifier: 1.2,
    pull_group: 3 //ext
  },
  "Condi Scourge Shisk" : {
    name: "Shisk",
    owner : "Triask.4189",
    armor : "light",
    combat : "magic",
    class: "necro",
    specialization : "scourge",
    min_rank: 4,
    max_rank: 7,
    hp_modifier: 1.1,
    spd_modifier: 1.1,
    atk_modifier: 1.2,
    def_modifier: 1.1,
    pull_group: 1 //ext
  },
  "Power Reaper Shisk" : {
    name: "Shisk",
    owner : "Triask.4189",
    armor : "light",
    combat : "melee",
    class: "necro",
    specialization : "scourge",
    min_rank: 4,
    max_rank: 7,
    hp_modifier: 1.2,
    spd_modifier: 0.8,
    atk_modifier: 1.3,
    def_modifier: 1.2,
    pull_group: 1 //ext
  },
  "Yilit" : {
    name: "Yilit",
    owner : "Triask.4189",
    armor : "light",
    combat : "melee",
    class: "mesmer",
    specialization : "none",
    min_rank: 3,
    max_rank: 5,
    hp_modifier: 1.1,
    spd_modifier: 0.9,
    atk_modifier: 1,
    def_modifier: 1.2,
    pull_group: 4 //ext
  },
  "Chrono Tank Yilit" : {
    name: "Chrono Tank Yilit",
    owner : "Triask.4189",
    armor : "light",
    combat : "melee",
    class: "mesmer",
    specialization : "chrono",
    min_rank: 3,
    max_rank: 6,
    hp_modifier: 1.3,
    spd_modifier: 0.9,
    atk_modifier: 0.9,
    def_modifier: 1.4,
    pull_group: 1 //ext
  },
  "Condi Mirage Yilit" : {
    name: "Condi Mirage Yilit",
    owner : "Triask.4189",
    armor : "light",
    combat : "melee",
    class: "mesmer",
    specialization : "mirage",
    min_rank: 3,
    max_rank: 6,
    hp_modifier: 1.1,
    spd_modifier: 1.3,
    atk_modifier: 1.3,
    def_modifier: 0.8,
    pull_group: 1 //ext
  },
  "Zipts" : {
    name: "Zipts",
    owner : "Triask.4189",
    armor : "heavy",
    combat : "melee",
    class: "guard",
    specialization : "firebrand",
    min_rank: 3,
    max_rank: 6,
    hp_modifier: 0.9,
    spd_modifier: 1.2,
    atk_modifier: 1.3,
    def_modifier: 0.9,
    pull_group: 1 //ext
  },
  "Firebrand Healer Zipts" : {
    name: "Firebrand Healer Zipts",
    owner : "Triask.4189",
    armor : "heavy",
    combat : "melee",
    class: "guard",
    specialization : "firebrand",
    min_rank: 3,
    max_rank: 6,
    hp_modifier: 1.4,
    spd_modifier: 1.2,
    atk_modifier: 0.8,
    def_modifier: 1.0,
    pull_group: 1 //ext
  },
  "Izieko" : {
    name: "Izieko",
    owner : "Triask.4189",
    armor : "medium",
    combat : "magic",
    class: "ranger",
    specialization : "none",
    min_rank: 2,
    max_rank: 5,
    hp_modifier: 1.1,
    spd_modifier: 1.0,
    atk_modifier: 1.1,
    def_modifier: 1.0,
    pull_group: 5 //ext
  },
  "Yeukrin" : {
    name: "Yeukrin",
    owner : "Triask.4189",
    armor : "medium",
    combat : "melee",
    class: "engie",
    specialization : "none",
    min_rank: 2,
    max_rank: 5,
    hp_modifier: 1.0,
    spd_modifier: 1.0,
    atk_modifier: 1.2,
    def_modifier: 1.0,
    pull_group: 5 //ext
  },
  "Qucul" : {
    name: "Qucul",
    owner : "Triask.4189",
    armor : "heavy",
    combat : "magic",
    class: "rev",
    specialization : "none",
    min_rank: 2,
    max_rank: 5,
    hp_modifier: 1.1,
    spd_modifier: 0.9,
    atk_modifier: 1,
    def_modifier: 1.2,
    pull_group: 5 //ext
  },
  "Xnitch" : {
    name: "Xnitch",
    owner : "Triask.4189",
    armor : "medium",
    combat : "melee",
    class: "thief",
    specialization : "none",
    min_rank: 1,
    max_rank: 4,
    hp_modifier: 0.9,
    spd_modifier: 1.3,
    atk_modifier: 1,
    def_modifier: 0.9,
    pull_group: 6 //ext
  },
  "Linyli" : {
    name: "Linyli",
    owner : "Triask.4189",
    armor : "heavy",
    combat : "ranged",
    class: "warrior",
    specialization : "none",
    min_rank: 1,
    max_rank: 4,
    hp_modifier: 1.1,
    spd_modifier: 0.9,
    atk_modifier: 1.1,
    def_modifier: 1.0,
    pull_group: 6 //ext
  },
  "Oquti" : {
    name: "Oquti",
    owner : "Triask.4189",
    armor : "light",
    combat : "magic",
    class: "ele",
    specialization : "none",
    min_rank: 1,
    max_rank: 3,
    hp_modifier: 0.8,
    spd_modifier: 0.9,
    atk_modifier: 1.4,
    def_modifier: 0.9,
    pull_group: 6 //ext
  },
  "Paired Deuces" : {
    name: "Paired Deuces",
    owner : "Triask.4189",
    armor : "medium",
    combat : "magic",
    class: "engie",
    specialization : "none",
    min_rank: 1,
    max_rank: 3,
    hp_modifier: 0.8,
    spd_modifier: 0.9,
    atk_modifier: 1.2,
    def_modifier: 1.0,
    pull_group: 7 //ext
  },
  // Anzy's Units
  "Sylvia Aria" : {
    name: "Sylvia Aria",
    owner : "Anzy.9237",
    armor : "medium",
    combat : "melee",
    class: "thief",
    specialization : "none",
    min_rank: 3,
    max_rank: 6,
    hp_modifier: 0.9,
    spd_modifier: 1.3,
    atk_modifier: 1.3,
    def_modifier: 0.9,
    pull_group: 3 //ext
  },
  "Alssie" : {
    name: "Alssie",
    owner : "Anzy.9237",
    armor : "medium",
    combat : "magic",
    class: "ranger",
    specialization : "none",
    min_rank: 2,
    max_rank: 5,
    hp_modifier: 1.4,
    spd_modifier: 1.0,
    atk_modifier: 0.9,
    def_modifier: 1.0,
    pull_group: 4 //ext
  },
  "Deilusia" : {
    name: "Deilusia",
    owner : "Anzy.9237",
    armor : "light",
    combat : "melee",
    class: "mesmer",
    specialization : "none",
    min_rank: 2,
    max_rank: 5,
    hp_modifier: 1.2,
    spd_modifier: 0.9,
    atk_modifier: 0.9,
    def_modifier: 1.4,
    pull_group: 4 //ext
  },
  "Tybalt Ashpaw" : {
    name: "Tybalt Ashpaw",
    owner : "Anzy.9237",
    armor : "light",
    combat : "ranged",
    class: "ele",
    specialization : "none",
    min_rank: 2,
    max_rank: 4,
    hp_modifier: 0.8,
    spd_modifier: 1.0,
    atk_modifier: 1.6,
    def_modifier: 0.8,
    pull_group: 5 //ext
  },
  "Faira Cete" : {
    name: "Faira Cete",
    owner : "Anzy.9237",
    armor : "heavy",
    combat : "magic",
    class: "warrior",
    specialization : "none",
    min_rank: 2,
    max_rank: 4,
    hp_modifier: 1.0,
    spd_modifier: 1.0,
    atk_modifier: 1.2,
    def_modifier: 1.0,
    pull_group: 5 //ext
  },
  "Engienius" : {
    name: "Engienius",
    owner : "Anzy.9237",
    armor : "medium",
    combat : "melee",
    class: "engie",
    specialization : "none",
    min_rank: 1,
    max_rank: 5,
    hp_modifier: 0.9,
    spd_modifier: 1.1,
    atk_modifier: 1.3,
    def_modifier: 0.9,
    pull_group: 5 //ext
  },
  "Living Phobia" : {
    name: "Living Phobia",
    owner : "Anzy.9237",
    armor : "light",
    combat : "magic",
    class: "necro",
    specialization : "none",
    min_rank: 1,
    max_rank: 4,
    hp_modifier: 1.1,
    spd_modifier: 0.9,
    atk_modifier: 1.0,
    def_modifier: 1.1,
    pull_group: 6 //ext
  },
  "Mimi Whyte" : {
    name: "Mimi Whyte",
    owner : "Anzy.9237",
    armor : "heavy",
    combat : "ranged",
    class: "guard",
    specialization : "none",
    min_rank: 1,
    max_rank: 4,
    hp_modifier: 0.9,
    spd_modifier: 1.0,
    atk_modifier: 1.3,
    def_modifier: 0.9,
    pull_group: 6 //ext
  },
  "Mystical" : {
    name: "Mystical",
    owner : "Anzy.9237",
    armor : "heavy",
    combat : "magic",
    class: "rev",
    specialization : "none",
    min_rank: 1,
    max_rank: 4,
    hp_modifier: 1.0,
    spd_modifier: 1.0,
    atk_modifier: 1.1,
    def_modifier: 1.0,
    pull_group: 6 //ext
  },
  "Wishful" : {
    name: "Wishful",
    owner : "Anzy.9237",
    armor : "light",
    combat : "ranged",
    class: "ele",
    specialization : "none",
    min_rank: 1,
    max_rank: 3,
    hp_modifier: 0.7,
    spd_modifier: 0.8,
    atk_modifier: 1.5,
    def_modifier: 0.8,
    pull_group: 7 //ext
  },
  "Anzer Panzer" : {
    name: "Anzer Panzer",
    owner : "Anzy.9237",
    armor : "heavy",
    combat : "ranged",
    class: "warrior",
    specialization : "none",
    min_rank: 1,
    max_rank: 3,
    hp_modifier: 1.0,
    spd_modifier: 0.9,
    atk_modifier: 1.0,
    def_modifier: 0.9,
    pull_group: 7 //ext
  },
  "Sketchy Art Student" : {
    name: "Sketchy Art Student",
    owner : "Anzy.9237",
    armor : "medium",
    combat : "magic",
    class: "ranger",
    specialization : "none",
    min_rank: 1,
    max_rank: 3,
    hp_modifier: 1.0,
    spd_modifier: 1.0,
    atk_modifier: 0.9,
    def_modifier: 0.9,
    pull_group: 3 //ext
  },
  "La Pestables" : {
    name: "Sylvia Aria",
    owner : "Anzy.9237",
    armor : "medium",
    combat : "melee",
    class: "thief",
    specialization : "none",
    min_rank: 1,
    max_rank: 3,
    hp_modifier: 1.1,
    spd_modifier: 0.9,
    atk_modifier: 0.9,
    def_modifier: 0.9,
    pull_group: 7 //ext
  },
  // Peste's Units
  "La Peste" : {
    name: "La Peste",
    owner : "fluffnut.7624",
    armor : "light",
    combat : "magic",
    class: "necromancer",
    specialization : "none",
    min_rank: 3,
    max_rank: 6,
    hp_modifier: 1.3,
    spd_modifier: 0.95,
    atk_modifier: 1,
    def_modifier: 1.15,
    pull_group: 3 //ext
  },
  "Iced Peppermint Tea" : {
    name: "Iced Peppermint Tea",
    owner : "fluffnut.7624",
    armor : "medium",
    combat : "magic",
    class: "ranger",
    specialization : "none",
    min_rank: 2,
    max_rank: 5,
    hp_modifier: 1.4,
    spd_modifier: 0.9,
    atk_modifier: 0.9,
    def_modifier: 1.1,
    pull_group: 4 //ext
  },
  "Enfant de la Lune" : {
    name: "Enfant de la Lune",
    owner : "fluffnut.7624",
    armor : "heavy",
    combat : "melee",
    class: "warrior",
    specialization : "none",
    min_rank: 2,
    max_rank: 5,
    hp_modifier: 0.9,
    spd_modifier: 1.1,
    atk_modifier: 1.2,
    def_modifier: 1.1,
    pull_group: 4 //ext
  },
  "Tem Peste" : {
    name: "Tem Peste",
    owner : "fluffnut.7624",
    armor : "light",
    combat : "magic",
    class: "ele",
    specialization : "none",
    min_rank: 2,
    max_rank: 5,
    hp_modifier: 0.9,
    spd_modifier: 1,
    atk_modifier: 1.1,
    def_modifier: 1.2,
    pull_group: 5 //ext
  },
  "Chere Ophelie" : {
    name: "Chere Ophelie",
    owner : "fluffnut.7624",
    armor : "heavy",
    combat : "ranged",
    class: "guard",
    specialization : "none",
    min_rank: 2,
    max_rank: 4,
    hp_modifier: 1.1,
    spd_modifier: 1.1,
    atk_modifier: 1.0,
    def_modifier: 1.05,
    pull_group: 5 //ext
  },
  "Christabel" : {
    name: "Christabel",
    owner : "fluffnut.7624",
    armor : "light",
    combat : "melee",
    class: "mesmer",
    specialization : "none",
    min_rank: 1,
    max_rank: 4,
    hp_modifier: 1.0,
    spd_modifier: 0.8,
    atk_modifier: 1.2,
    def_modifier: 1.0,
    pull_group: 6 //ext
  },
  "Revelries" : {
    name: "Revelries",
    owner : "fluffnut.7624",
    armor : "heavy",
    combat : "magic",
    class: "rev",
    specialization : "none",
    min_rank: 1,
    max_rank: 5,
    hp_modifier: 0.9,
    spd_modifier: 0.95,
    atk_modifier: 1,
    def_modifier: 1.1,
    pull_group: 6 //ext
  },/*
  "xxxxxxxx" : {
    name: "xxxxxxxxx",
    owner : "fluffnut.7624",
    armor : "light",
    combat : "magic",
    class: "necro",
    specialization : "none",
    min_rank: 3,
    max_rank: 6,
    hp_modifier: 1.3,
    spd_modifier: 0.95,
    atk_modifier: 1,
    def_modifier: 1.15,
    pull_group: 3 //ext
  },
  "xxxxxxxx" : {
    name: "xxxxxxxxx",
    owner : "fluffnut.7624",
    armor : "light",
    combat : "magic",
    class: "necro",
    specialization : "none",
    min_rank: 3,
    max_rank: 6,
    hp_modifier: 1.3,
    spd_modifier: 0.95,
    atk_modifier: 1,
    def_modifier: 1.15,
    pull_group: 3 //ext
  },
  "xxxxxxxx" : {
    name: "xxxxxxxxx",
    owner : "fluffnut.7624",
    armor : "light",
    combat : "magic",
    class: "necro",
    specialization : "none",
    min_rank: 3,
    max_rank: 6,
    hp_modifier: 1.3,
    spd_modifier: 0.95,
    atk_modifier: 1,
    def_modifier: 1.15,
    pull_group: 3 //ext
  },
  "xxxxxxxx" : {
    name: "xxxxxxxxx",
    owner : "fluffnut.7624",
    armor : "light",
    combat : "magic",
    class: "necro",
    specialization : "none",
    min_rank: 3,
    max_rank: 6,
    hp_modifier: 1.3,
    spd_modifier: 0.95,
    atk_modifier: 1,
    def_modifier: 1.15,
    pull_group: 3 //ext
  },
  "xxxxxxxx" : {
    name: "xxxxxxxxx",
    owner : "fluffnut.7624",
    armor : "light",
    combat : "magic",
    class: "necro",
    specialization : "none",
    min_rank: 3,
    max_rank: 6,
    hp_modifier: 1.3,
    spd_modifier: 0.95,
    atk_modifier: 1,
    def_modifier: 1.15,
    pull_group: 3 //ext
  },
  "xxxxxxxx" : {
    name: "xxxxxxxxx",
    owner : "fluffnut.7624",
    armor : "light",
    combat : "magic",
    class: "necro",
    specialization : "none",
    min_rank: 3,
    max_rank: 6,
    hp_modifier: 1.3,
    spd_modifier: 0.95,
    atk_modifier: 1,
    def_modifier: 1.15,
    pull_group: 3 //ext
  },*/
  "Aeghbert" : {
    name: "Aeghbert",
    owner : "Liko.6825",
    armor : "medium",
    combat : "melee",
    class: "thief",
    specialization : "none",
    min_rank: 4,
    max_rank: 7,
    hp_modifier: 0.95,
    spd_modifier: 1.2,
    atk_modifier: 1.2,
    def_modifier: 1.1,
    pull_group: 3 //ext
  },
  "Ninja As Guardian" : {
    name: "Ninja As Guardian",
    owner : "IMA NINJA.4061",
    armor : "heavy",
    combat : "melee",
    class: "guardian",
    specialization : "none",
    min_rank: 4,
    max_rank: 7,
    hp_modifier: 1.3,
    spd_modifier: 0.9,
    atk_modifier: 1.15,
    def_modifier: 1.05,
    pull_group: 3 //ext
  },
  "Neushmy" : {
    name: "Neushmy",
    owner : "cjsb.4569",
    armor : "medium",
    combat : "ranged",
    class: "ranger",
    specialization : "none",
    min_rank: 2,
    max_rank: 6,
    hp_modifier: 1.1,
    spd_modifier: 0.95,
    atk_modifier: 1,
    def_modifier: 1.1,
    pull_group: 4 //ext
  },
  "Ginviere" : {
    name: "Ginviere",
    owner : "cjsb.4569",
    armor : "light",
    combat : "magic",
    class: "elementalist",
    specialization : "none",
    min_rank: 1,
    max_rank: 3,
    hp_modifier: 0.9,
    spd_modifier: 0.9,
    atk_modifier: 1.2,
    def_modifier: 0.9,
    pull_group: 7 //ext
  },
}
